export const exploreStrings = {
  title: "Firestore Service Test Suite",
  description: "Set IDs for testing operations that require existing documents:",
  operatorIdPlaceholder: "Selected Operator ID",
  machineIdPlaceholder: "Selected Machine ID",
  workOrderIdPlaceholder: "Selected Work Order ID",
  createOperator: "Create Operator",
  getOperator: "Get Operator",
  updateOperatorStatus: "Update Status",
  getOperatorByEmployeeId: "Get by Employee ID",
  getAllOperators: "Get All Operators",
  createMachine: "Create Machine",
  getMachine: "Get Machine",
  updateMachineFuelLevel: "Update Fuel Level",
  updateMachineLocation: "Update Location",
  getMachinesByStatus: "Get by Status",
  getAvailableMachines: "Get Available",
  assignMachineToOperator: "Assign to Operator",
  getAllMachines: "Get All Machines",
  createWorkOrder: "Create Work Order",
  getWorkOrder: "Get Work Order",
  getWorkOrdersByOperator: "Get by Operator",
  getActiveWorkOrders: "Get Active Orders",
  updateWorkOrderStatus: "Update Status",
  updateCheckpointStatus: "Update Checkpoint",
  createScheduledTask: "Create Task",
  getTasksByOperator: "Get Tasks by Operator",
  createInspection: "Create Inspection",
  createAlert: "Create Alert",
  getActiveAlerts: "Get Active Alerts",
  getActiveAlertsForOperator: "Get Alerts for Operator",
  addToOfflineQueue: "Add to Queue",
  getPendingOfflineItems: "Get Pending Items",
  batchCreateOperators: "Batch Create Operators",
  clearResults: "Clear Results",
  recentTestResults: "Recent Test Results",
  availableOperations: "Available Operations",
  genericCrud: "Generic CRUD:",
  operators: "Operators:",
  machines: "Machines:",
  workOrders: "Work Orders:",
  alerts: "Alerts:",
  batchOperations: "Batch Operations:",
  offlineQueue: "Offline Queue:",
};